// ============================================================
// components/birthday/photos.ts
//
// The photographs, and how each one wants to be cropped.
//
// `focus` is the object-position used when a photo has to fill a
// frame that is not its own shape. A face near the top of a tall
// phone photo gets cut off by the default centre crop, so every
// picture says where its subject actually is.
//
// The optimised files are generated by:
//     node scripts/prepare-birthday-photos.mjs
// which reads the originals and writes /public/media/birthday/.
// ============================================================

export interface Photo {
  /** File name under /media/birthday/ */
  src: string
  /** object-position for a fill crop. */
  focus: string
  /** Shown in the lightbox and read by screen readers. */
  caption: string
  /** Portrait photos get a taller card in the drifting rail. */
  portrait?: boolean
  /** The pictures good enough to carry the full-bleed hero. */
  hero?: boolean
}

export const PHOTOS: Photo[] = [
  {
    src: 'us-01.jpg',
    focus: '50% 32%',
    caption: 'The way you look at me',
    portrait: true,
    hero: true,
  },
  {
    src: 'us-02.jpg',
    focus: '50% 30%',
    caption: 'Us, exactly as we are',
    portrait: true,
    hero: true,
  },
  {
    src: 'us-03.jpg',
    focus: '50% 38%',
    caption: 'Somewhere in the middle of an ordinary day',
    hero: true,
  },
  {
    src: 'us-04.jpg',
    focus: '50% 34%',
    caption: 'One straw, two of us',
    portrait: true,
    hero: true,
  },
  {
    src: 'us-05.jpg',
    focus: '50% 34%',
    caption: 'Home, and dinner, and you',
    hero: true,
  },
  {
    src: 'you-01.jpg',
    focus: '50% 28%',
    caption: 'Mid-sentence, and still the best thing in the room',
    portrait: true,
  },
  {
    src: 'you-02.jpg',
    focus: '50% 30%',
    caption: 'That laugh',
    portrait: true,
  },
  {
    src: 'you-03.jpg',
    focus: '50% 30%',
    caption: 'Joy, held in both arms',
    portrait: true,
  },
  {
    src: 'collage-love.jpg',
    focus: '50% 45%',
    caption: 'All we need is love',
  },
]

/** The pictures the hero cross-fade cycles through. */
export const HERO_PHOTOS = PHOTOS.filter(p => p.hero)
