// ============================================================
// components/birthday/photos.generated.ts
//
// Written by scripts/birthday-photos.mjs — but safe to edit.
//
// Empty until the photographs are added. Select them in Photos.app
// and run:
//
//     node scripts/birthday-photos.mjs --photos
//
// and this file fills itself in. The page renders whatever ends up
// here, so there is no limit on how many there are — run it again
// any time to add more.
//
// Three things are worth changing by hand afterwards:
//   caption  what the picture says when she taps it. Your wording
//            is kept when the script runs again.
//   focus    where the crop is anchored, as background-position.
//            Nudge the second number down if a face gets cut off
//            at the top, up if it gets cut off at the chin.
//   hero     whether this one takes a turn filling the screen
//            behind her name. Best on photographs with room
//            around the subject.
// ============================================================

import type { Photo } from './photos'

export const GENERATED: Photo[] = [
  {
    src: 'p-01.jpg',
    thumb: 'p-01-t.jpg',
    focus: '50% 38%',
    caption: 'Us, exactly as we are',
    portrait: true,
    hero: true,
  },
  {
    src: 'p-02.jpg',
    thumb: 'p-02-t.jpg',
    focus: '52% 12%',
    caption: 'This one. Especially this one.',
    portrait: true,
    hero: true,
  },
  {
    src: 'p-03.jpg',
    thumb: 'p-03-t.jpg',
    focus: '63% 20%',
    caption: 'The way you look at me',
    portrait: true,
    hero: true,
  },
  {
    src: 'p-04.jpg',
    thumb: 'p-04-t.jpg',
    focus: '64% 47%',
    caption: 'My whole heart, standing right there',
    portrait: true,
    hero: true,
  },
  {
    src: 'p-05.jpg',
    thumb: 'p-05-t.jpg',
    focus: '37% 38%',
    caption: 'Look at us',
    portrait: true,
    hero: true,
  },
  {
    src: 'p-06.jpg',
    thumb: 'p-06-t.jpg',
    focus: '69% 43%',
    caption: 'I would live this day again',
    hero: true,
  },
  {
    src: 'p-07.jpg',
    thumb: 'p-07-t.jpg',
    focus: '34% 39%',
    caption: 'That laugh',
    portrait: true,
  },
  {
    src: 'p-08.jpg',
    thumb: 'p-08-t.jpg',
    focus: '22% 36%',
    caption: 'Nothing special happening, and I was so happy',
    portrait: true,
  },
  {
    src: 'p-09.jpg',
    thumb: 'p-09-t.jpg',
    focus: '50% 38%',
    caption: 'You, mid-sentence, being wonderful',
    portrait: true,
  },
  {
    src: 'p-10.jpg',
    thumb: 'p-10-t.jpg',
    focus: '50% 38%',
    caption: 'Home is wherever this is',
  },
  {
    src: 'p-11.jpg',
    thumb: 'p-11-t.jpg',
    focus: '50% 38%',
    caption: 'Still my favourite person',
  },
  {
    src: 'p-12.jpg',
    thumb: 'p-12-t.jpg',
    focus: '50% 38%',
    caption: 'Ours',
    portrait: true,
  },
  {
    src: 'p-13.jpg',
    thumb: 'p-13-t.jpg',
    focus: '39% 31%',
    caption: 'A perfectly ordinary, perfectly good day',
    portrait: true,
  },
  {
    src: 'p-14.jpg',
    thumb: 'p-14-t.jpg',
    focus: '44% 22%',
    caption: 'You make everything softer',
    portrait: true,
  },
  {
    src: 'p-15.jpg',
    thumb: 'p-15-t.jpg',
    focus: '57% 33%',
    caption: 'This is what lucky looks like',
    portrait: true,
  },
  {
    src: 'p-16.jpg',
    thumb: 'p-16-t.jpg',
    focus: '44% 25%',
    caption: 'I never want to stop taking these',
    portrait: true,
  },
  {
    src: 'p-17.jpg',
    thumb: 'p-17-t.jpg',
    focus: '50% 38%',
    caption: 'The best thing in the room, as usual',
    portrait: true,
  },
  {
    src: 'p-18.jpg',
    thumb: 'p-18-t.jpg',
    focus: '50% 38%',
    caption: 'I remember exactly what you said next',
    portrait: true,
  },
  {
    src: 'p-19.jpg',
    thumb: 'p-19-t.jpg',
    focus: '50% 38%',
    caption: 'Somewhere in the middle of a Tuesday',
    portrait: true,
  },
  {
    src: 'p-20.jpg',
    thumb: 'p-20-t.jpg',
    focus: '50% 38%',
    caption: 'Caught you being happy',
    portrait: true,
  },
  {
    src: 'p-21.jpg',
    thumb: 'p-21-t.jpg',
    focus: '46% 27%',
    caption: 'This face. Every time.',
    portrait: true,
  },
  {
    src: 'p-22.jpg',
    thumb: 'p-22-t.jpg',
    focus: '50% 38%',
    caption: 'You, and nothing else worth looking at',
    portrait: true,
  },
  {
    src: 'p-23.jpg',
    thumb: 'p-23-t.jpg',
    focus: '50% 38%',
    caption: 'I could watch you talk all day',
    portrait: true,
  },
  {
    src: 'p-24.jpg',
    thumb: 'p-24-t.jpg',
    focus: '50% 38%',
    caption: 'The one where you were laughing at me',
    portrait: true,
  },
  {
    src: 'p-25.jpg',
    thumb: 'p-25-t.jpg',
    focus: '54% 51%',
    caption: 'Half asleep and still lovely',
    portrait: true,
  },
  {
    src: 'p-26.jpg',
    thumb: 'p-26-t.jpg',
    focus: '50% 38%',
    caption: 'My favourite kind of evening',
    portrait: true,
  },
  {
    src: 'p-27.jpg',
    thumb: 'p-27-t.jpg',
    focus: '50% 38%',
    caption: 'You have no idea what you do to me',
    portrait: true,
  },
  {
    src: 'p-28.jpg',
    thumb: 'p-28-t.jpg',
    focus: '50% 38%',
    caption: 'Right here. This is the feeling.',
    portrait: true,
  },
  {
    src: 'p-29.jpg',
    thumb: 'p-29-t.jpg',
    focus: '50% 38%',
    caption: 'Nothing to say, just wanted to look',
    portrait: true,
  },
  {
    src: 'p-30.jpg',
    thumb: 'p-30-t.jpg',
    focus: '59% 37%',
    caption: 'The very best part of my day',
    portrait: true,
  },
  {
    src: 'p-31.jpg',
    thumb: 'p-31-t.jpg',
    focus: '50% 40%',
    caption: 'You, being ridiculous, being perfect',
    portrait: true,
  },
  {
    src: 'p-32.jpg',
    thumb: 'p-32-t.jpg',
    focus: '50% 38%',
    caption: 'I kept this one',
    portrait: true,
  },
  {
    src: 'p-33.jpg',
    thumb: 'p-33-t.jpg',
    focus: '45% 33%',
    caption: 'Late, and neither of us wanting to hang up',
    portrait: true,
  },
  {
    src: 'p-34.jpg',
    thumb: 'p-34-t.jpg',
    focus: '50% 38%',
    caption: 'That look you do',
    portrait: true,
  },
  {
    src: 'p-35.jpg',
    thumb: 'p-35-t.jpg',
    focus: '42% 34%',
    caption: 'I fall for this face on a loop',
    portrait: true,
  },
  {
    src: 'p-36.jpg',
    thumb: 'p-36-t.jpg',
    focus: '42% 48%',
    caption: 'Small moment, enormous to me',
    portrait: true,
  },
  {
    src: 'p-37.jpg',
    thumb: 'p-37-t.jpg',
    focus: '48% 50%',
    caption: 'You make the ordinary days the good ones',
    portrait: true,
  },
  {
    src: 'p-38.jpg',
    thumb: 'p-38-t.jpg',
    focus: '62% 57%',
    caption: 'Every single time',
    portrait: true,
  },
  {
    src: 'p-39.jpg',
    thumb: 'p-39-t.jpg',
    focus: '50% 38%',
    caption: 'This is my whole world, casually',
    portrait: true,
  },
  {
    src: 'p-40.jpg',
    thumb: 'p-40-t.jpg',
    focus: '50% 38%',
    caption: 'Nothing posed, nothing planned',
    portrait: true,
  },
  {
    src: 'p-41.jpg',
    thumb: 'p-41-t.jpg',
    focus: '50% 38%',
    caption: 'I was so glad you called',
    portrait: true,
  },
  {
    src: 'p-42.jpg',
    thumb: 'p-42-t.jpg',
    focus: '41% 40%',
    caption: 'The face I think about all day',
    portrait: true,
  },
  {
    src: 'p-43.jpg',
    thumb: 'p-43-t.jpg',
    focus: '50% 38%',
    caption: 'You laughing before the funny part',
    portrait: true,
  },
  {
    src: 'p-44.jpg',
    thumb: 'p-44-t.jpg',
    focus: '55% 61%',
    caption: 'Softest heart I know',
    portrait: true,
  },
  {
    src: 'p-45.jpg',
    thumb: 'p-45-t.jpg',
    focus: '46% 28%',
    caption: 'I\'d have taken a hundred more',
    portrait: true,
  },
  {
    src: 'p-46.jpg',
    thumb: 'p-46-t.jpg',
    focus: '50% 38%',
    caption: 'Mid-story, and I wasn\'t listening properly',
    portrait: true,
  },
  {
    src: 'p-47.jpg',
    thumb: 'p-47-t.jpg',
    focus: '58% 48%',
    caption: 'Just you being you',
    portrait: true,
  },
  {
    src: 'p-48.jpg',
    thumb: 'p-48-t.jpg',
    focus: '50% 38%',
    caption: 'This is what I mean when I say I love you',
    portrait: true,
  },
  {
    src: 'p-49.jpg',
    thumb: 'p-49-t.jpg',
    focus: '50% 38%',
    caption: 'The reason I look at my phone so much',
    portrait: true,
  },
  {
    src: 'p-51.jpg',
    thumb: 'p-51-t.jpg',
    focus: '66% 76%',
    caption: 'My person',
    portrait: true,
  },
  {
    src: 'p-52.jpg',
    thumb: 'p-52-t.jpg',
    focus: '50% 38%',
    caption: 'Nobody makes me laugh like this',
    portrait: true,
  },
  {
    src: 'p-53.jpg',
    thumb: 'p-53-t.jpg',
    focus: '50% 38%',
    caption: 'Quietly the best thing that happened to me',
    portrait: true,
  },
  {
    src: 'p-54.jpg',
    thumb: 'p-54-t.jpg',
    focus: '58% 35%',
    caption: 'I love this one more than I can say',
    portrait: true,
  },
  {
    src: 'p-55.jpg',
    thumb: 'p-55-t.jpg',
    focus: '50% 38%',
    caption: 'You, and my entire heart',
    portrait: true,
  },
  {
    src: 'p-56.jpg',
    thumb: 'p-56-t.jpg',
    focus: '50% 38%',
    caption: 'Some days I just stare',
    portrait: true,
  },
  {
    src: 'p-57.jpg',
    thumb: 'p-57-t.jpg',
    focus: '57% 45%',
    caption: 'The one I\'d keep if I could keep only one',
    portrait: true,
  },
  {
    src: 'p-58.jpg',
    thumb: 'p-58-t.jpg',
    focus: '50% 38%',
    caption: 'You make me want every single tomorrow',
    portrait: true,
  },
  {
    src: 'p-59.jpg',
    thumb: 'p-59-t.jpg',
    focus: '50% 38%',
    caption: 'This is us. I\'d choose it again.',
    portrait: true,
  },
  {
    src: 'p-60.jpg',
    thumb: 'p-60-t.jpg',
    focus: '36% 32%',
    caption: 'Completely, hopelessly yours',
    portrait: true,
  },
  {
    src: 'p-61.jpg',
    thumb: 'p-61-t.jpg',
    focus: '50% 38%',
    caption: 'You are the plan, not part of it',
    portrait: true,
  },
  {
    src: 'p-62.jpg',
    thumb: 'p-62-t.jpg',
    focus: '61% 40%',
    caption: 'And I love you soooo much',
    portrait: true,
  },
]
